name: Deploy to GitHub Pages

on:
  # Run workflow on pushes to the main branch
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4
      - name: Install, build, and upload your site
        uses: withastro/action@v2
        with:
          # Pass the secret to the build environment
          VITE_SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          
        # The withastro/action@v2 action will:
        # 1. Install Node.js
        # 2. Install your project's dependencies
        # 3. Build your Astro site based on your config (output: 'static')
        # 4. Prepare an artifact for deployment

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4